### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by anonimo82** [plugdata-team/plugdata-ofelia#1]
Hello everyone.
How can I install this in plugdata?

Thanks for any help.

Regards.

**Comment by timothyschoen** [comment]
Hi!

I'm gonna upload an improved version today, I'll post here when it's ready. What OS do you use?

In the meantime, you can already install the most recent nightly build of plugdata (https://plugdata.org/download.html), which you'll need to run plugdata-ofelia. If it didn't work before, it's because I changed some things in plugdata already to make it compatible with my upcoming version, sorry for that.

**Comment by anonimo82** [comment]
Hello, using Windows 10 here.
Thanks, I'll try this tomorrow, I can't right now

**Comment by anonimo82** [comment]
Hello @timothyschoen , I installed PlugData nightly build.
Now what to install Ofelia-PlugData?

Thanks.

Edit: Nevermind, I found the instructions in the releases section. Thanks a lot for making this possible =)

**Comment by timothyschoen** [comment]
Hi, I'm still fixing up some Linux issues for the next release, turned out to be harder than I expected. Here's the Windows version already for you:

[plugdata-ofelia-windows.zip](https://github.com/plugdata-team/plugdata-ofelia/files/11331242/plugdata-ofelia-windows.zip)

Add the "ofelia" and the "abs" folder inside the zip to plugdata's search path, and it should work!
